// WARNING: This file has been autogenerated from the PILOUT file.
// Manual modifications are not recommended and may be overwritten.
#![allow(clippy::all)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]

use proofman_common as common;
pub use proofman_macros::trace;
pub use proofman_macros::values;

use std::fmt;

use rayon::prelude::*;

#[allow(dead_code)]
type FieldExtension<F> = [F; 3];

pub const PILOUT_HASH: &str = "48cc399e861851b12a24f9a9e1178fe9886e58dbccfe27631809e74fe2272fd9";

//AIRGROUP CONSTANTS

pub const FIBO_CPU_AIRGROUP_ID: usize = 0;

//AIR CONSTANTS

pub const FIBONACCI_SQUARE_AIR_IDS: &[usize] = &[0];

pub const MODULE_AIR_IDS: &[usize] = &[1];

pub const SPECIFIED_RANGES_AIR_IDS: &[usize] = &[2];

//PUBLICS
use serde::Deserialize;
use serde::Serialize;
use serde_arrays;

fn default_array_rom_root() -> [u64; 4] {
    [0; 4]
}

#[derive(Debug, Serialize, Deserialize)]
pub struct BuildPublics {
    #[serde(default)]
    pub module: u64,
    #[serde(default)]
    pub in1: u64,
    #[serde(default)]
    pub in2: u64,
    #[serde(default)]
    pub out: u64,
    #[serde(default = "default_array_rom_root", with = "serde_arrays")]
    pub rom_root: [u64; 4],
}

impl Default for BuildPublics {
    fn default() -> Self {
        Self { module: 0, in1: 0, in2: 0, out: 0, rom_root: [0; 4] }
    }
}

values!(BuildPublicValues<F> {
 module: F, in1: F, in2: F, out: F, rom_root: [F; 4],
});

values!(BuildProofValues<F> {
 value1: F, value2: F,
});

trace!(FibonacciSquareFixed<F> {
 L1: F, __L1__: F,
},  0, 0, 4194304 );

trace!(FibonacciSquareTrace<F> {
 a: F, b: F,
},  0, 0, 4194304 );

trace!(ModuleFixed<F> {
 SEGMENT_LN: F, __L1__: F,
},  0, 1, 1048576 );

trace!(ModuleTrace<F> {
 x: F, q: F, x_mod: F,
},  0, 1, 1048576 );

trace!(SpecifiedRangesFixed<F> {
 RANGE: [F; 1], __L1__: F,
},  0, 2, 256 );

trace!(SpecifiedRangesTrace<F> {
 mul: [F; 1],
},  0, 2, 256 );

trace!(FibonacciSquareRomTrace<F> {
 line: F, flags: F,
}, 0, 0, 4194304, 0 );

values!(FibonacciSquareAirValues<F> {
 fibo1: [F; 2], fibo3: FieldExtension<F>,
});

values!(ModuleAirValues<F> {
 last_segment: F,
});

values!(FibonacciSquareAirGroupValues<F> {
 gsum_result: FieldExtension<F>,
});

values!(ModuleAirGroupValues<F> {
 gsum_result: FieldExtension<F>,
});

values!(SpecifiedRangesAirGroupValues<F> {
 gsum_result: FieldExtension<F>,
});
