// WARNING: This file has been autogenerated from the PILOUT file.
// Manual modifications are not recommended and may be overwritten.
#![allow(clippy::all)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]

use proofman_common as common;
use proofman_common::GenericTrace;
use proofman_common::PackedInfoConst;
pub use proofman_macros::trace_row;
pub use proofman_macros::values;
use fields::PrimeField64;
use std::fmt;

#[allow(dead_code)]
type FieldExtension<F> = [F; 3];

pub const PILOUT_HASH: &str = "904eb62e7f7dc4361e75780eabe8e1d96374d63555f3f6749eef45d1231beaa5";

pub const MERKLE_TREE_ARITY: u64 = 4;

//AIRGROUP CONSTANTS

pub const GROUP_1_AIRGROUP_ID: usize = 0;

pub const GROUP_2_AIRGROUP_ID: usize = 1;

pub const GROUP_3_AIRGROUP_ID: usize = 2;

//AIR CONSTANTS

pub const PROD_BUS_AIR_IDS: &[usize] = &[0];

pub const SUM_BUS_AIR_IDS: &[usize] = &[1];

pub const BOTH_BUSES_AIR_IDS: &[usize] = &[2];

pub const SB_AIR_IDS: &[usize] = &[0];

pub const PB_AIR_IDS: &[usize] = &[0];

  
trace_row!(ProdBusFixedRow<F> {
 __L1__: F,
});
pub type ProdBusFixed<F> = GenericTrace<ProdBusFixedRow<F>, 16, 0, 0>;

trace_row!(ProdBusTraceRow<F> {
 a:F, b:F,
});
pub type ProdBusTrace<F> = GenericTrace<ProdBusTraceRow<F>, 16, 0, 0>;


trace_row!(SumBusFixedRow<F> {
 __L1__: F,
});
pub type SumBusFixed<F> = GenericTrace<SumBusFixedRow<F>, 32, 0, 1>;

trace_row!(SumBusTraceRow<F> {
 a:F, b:F,
});
pub type SumBusTrace<F> = GenericTrace<SumBusTraceRow<F>, 32, 0, 1>;


trace_row!(BothBusesFixedRow<F> {
 __L1__: F,
});
pub type BothBusesFixed<F> = GenericTrace<BothBusesFixedRow<F>, 16, 0, 2>;

trace_row!(BothBusesTraceRow<F> {
 a:F, b:F, c:F, d:F,
});
pub type BothBusesTrace<F> = GenericTrace<BothBusesTraceRow<F>, 16, 0, 2>;


trace_row!(SBFixedRow<F> {
 __L1__: F,
});
pub type SBFixed<F> = GenericTrace<SBFixedRow<F>, 32, 1, 0>;

trace_row!(SBTraceRow<F> {
 a:F, b:F,
});
pub type SBTrace<F> = GenericTrace<SBTraceRow<F>, 32, 1, 0>;


trace_row!(PBFixedRow<F> {
 __L1__: F,
});
pub type PBFixed<F> = GenericTrace<PBFixedRow<F>, 16, 2, 0>;

trace_row!(PBTraceRow<F> {
 a:F, b:F,
});
pub type PBTrace<F> = GenericTrace<PBTraceRow<F>, 16, 2, 0>;


values!(ProdBusAirGroupValues<F> {
 gprod_result: FieldExtension<F>, gsum_result: FieldExtension<F>,
});

values!(SumBusAirGroupValues<F> {
 gprod_result: FieldExtension<F>, gsum_result: FieldExtension<F>,
});

values!(BothBusesAirGroupValues<F> {
 gprod_result: FieldExtension<F>, gsum_result: FieldExtension<F>,
});

values!(SBAirGroupValues<F> {
 gsum_result: FieldExtension<F>,
});

values!(PBAirGroupValues<F> {
 gprod_result: FieldExtension<F>,
});

pub const PACKED_INFO: &[(usize, usize, PackedInfoConst)] = &[
];