// WARNING: This file has been autogenerated from the PILOUT file.
// Manual modifications are not recommended and may be overwritten.
#![allow(clippy::all)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]

use proofman_common as common;
use proofman_common::GenericTrace;
use proofman_common::PackedInfoConst;
pub use proofman_macros::trace_row;
pub use proofman_macros::values;
use fields::PrimeField64;
use std::fmt;

#[allow(dead_code)]
type FieldExtension<F> = [F; 3];

pub const PILOUT_HASH: &str = "5a40690fe07cb56fa782ae5e33ad2ab84f2d2be4d3db96b03cb0e4f9891c6bb2";

pub const MERKLE_TREE_ARITY: u64 = 4;

//AIRGROUP CONSTANTS

pub const SIMPLE_AIRGROUP_ID: usize = 0;

//AIR CONSTANTS

pub const SIMPLE_LEFT_AIR_IDS: &[usize] = &[0];

pub const SIMPLE_RIGHT_AIR_IDS: &[usize] = &[1];

pub const U_8_AIR_AIR_IDS: &[usize] = &[2];

pub const U_16_AIR_AIR_IDS: &[usize] = &[3];

pub const SPECIFIED_RANGES_AIR_IDS: &[usize] = &[4];

  
trace_row!(SimpleLeftFixedRow<F> {
 __L1__: F,
});
pub type SimpleLeftFixed<F> = GenericTrace<SimpleLeftFixedRow<F>, 8, 0, 0>;

trace_row!(SimpleLeftTraceRow<F> {
 a:F, b:F, c:F, d:F, e:F, f:F, g:F, h:F, k:[F; 7],
});
pub type SimpleLeftTrace<F> = GenericTrace<SimpleLeftTraceRow<F>, 8, 0, 0>;


trace_row!(SimpleRightFixedRow<F> {
 __L1__: F,
});
pub type SimpleRightFixed<F> = GenericTrace<SimpleRightFixedRow<F>, 8, 0, 1>;

trace_row!(SimpleRightTraceRow<F> {
 a:F, b:F, c:F, d:F, mul:F,
});
pub type SimpleRightTrace<F> = GenericTrace<SimpleRightTraceRow<F>, 8, 0, 1>;


trace_row!(U8AirFixedRow<F> {
 RANGE: [F; 2], __L1__: F,
});
pub type U8AirFixed<F> = GenericTrace<U8AirFixedRow<F>, 128, 0, 2>;

trace_row!(U8AirTraceRow<F> {
 mul:[F; 2],
});
pub type U8AirTrace<F> = GenericTrace<U8AirTraceRow<F>, 128, 0, 2>;


trace_row!(U16AirFixedRow<F> {
 RANGE: [F; 4], __L1__: F,
});
pub type U16AirFixed<F> = GenericTrace<U16AirFixedRow<F>, 16384, 0, 3>;

trace_row!(U16AirTraceRow<F> {
 mul:[F; 4],
});
pub type U16AirTrace<F> = GenericTrace<U16AirTraceRow<F>, 16384, 0, 3>;


trace_row!(SpecifiedRangesFixedRow<F> {
 OPID: [F; 11], VALS: [F; 11], __L1__: F,
});
pub type SpecifiedRangesFixed<F> = GenericTrace<SpecifiedRangesFixedRow<F>, 64, 0, 4>;

trace_row!(SpecifiedRangesTraceRow<F> {
 mul:[F; 11],
});
pub type SpecifiedRangesTrace<F> = GenericTrace<SpecifiedRangesTraceRow<F>, 64, 0, 4>;


values!(SimpleLeftAirGroupValues<F> {
 gsum_result: FieldExtension<F>,
});

values!(SimpleRightAirGroupValues<F> {
 gsum_result: FieldExtension<F>,
});

values!(U8AirAirGroupValues<F> {
 gsum_result: FieldExtension<F>,
});

values!(U16AirAirGroupValues<F> {
 gsum_result: FieldExtension<F>,
});

values!(SpecifiedRangesAirGroupValues<F> {
 gsum_result: FieldExtension<F>,
});

pub const PACKED_INFO: &[(usize, usize, PackedInfoConst)] = &[
];