// WARNING: This file has been autogenerated from the PILOUT file.
// Manual modifications are not recommended and may be overwritten.
#![allow(clippy::all)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]

use proofman_common as common;
use proofman_common::GenericTrace;
use proofman_common::PackedInfoConst;
pub use proofman_macros::trace_row;
pub use proofman_macros::values;
use fields::PrimeField64;
use std::fmt;

#[allow(dead_code)]
type FieldExtension<F> = [F; 3];

pub const PILOUT_HASH: &str = "82340f76128a3e3df658762de3378af60f37b39f201ad2a7f79ec47330f19552";

pub const MERKLE_TREE_ARITY: u64 = 4;

//AIRGROUP CONSTANTS

pub const RANGE_CHECK_3_AIRGROUP_ID: usize = 0;

pub const RANGE_CHECK_2_AIRGROUP_ID: usize = 1;

pub const RANGE_CHECK_1_AIRGROUP_ID: usize = 2;

pub const RANGE_CHECK_4_AIRGROUP_ID: usize = 3;

pub const MULTI_RANGE_CHECK_1_AIRGROUP_ID: usize = 4;

pub const MULTI_RANGE_CHECK_2_AIRGROUP_ID: usize = 5;

pub const RANGE_CHECK_DYNAMIC_1_AIRGROUP_ID: usize = 6;

pub const RANGE_CHECK_DYNAMIC_2_AIRGROUP_ID: usize = 7;

pub const RANGE_CHECK_MIX_AIRGROUP_ID: usize = 8;

pub const U_8_AIR_AIRGROUP_ID: usize = 9;

pub const SPECIFIED_RANGES_AIRGROUP_ID: usize = 10;

//AIR CONSTANTS

pub const RANGE_CHECK_3_AIR_IDS: &[usize] = &[0];

pub const RANGE_CHECK_2_AIR_IDS: &[usize] = &[0];

pub const RANGE_CHECK_1_AIR_IDS: &[usize] = &[0];

pub const RANGE_CHECK_4_AIR_IDS: &[usize] = &[0];

pub const U_16_AIR_AIR_IDS: &[usize] = &[1];

pub const MULTI_RANGE_CHECK_1_AIR_IDS: &[usize] = &[0];

pub const MULTI_RANGE_CHECK_2_AIR_IDS: &[usize] = &[0];

pub const RANGE_CHECK_DYNAMIC_1_AIR_IDS: &[usize] = &[0];

pub const RANGE_CHECK_DYNAMIC_2_AIR_IDS: &[usize] = &[0];

pub const RANGE_CHECK_MIX_AIR_IDS: &[usize] = &[0];

pub const U_8_AIR_AIR_IDS: &[usize] = &[0];

pub const SPECIFIED_RANGES_AIR_IDS: &[usize] = &[0];

  
trace_row!(RangeCheck3FixedRow<F> {
 __L1__: F,
});
pub type RangeCheck3Fixed<F> = GenericTrace<RangeCheck3FixedRow<F>, 32, 0, 0>;

trace_row!(RangeCheck3TraceRow<F> {
 c1:F, c2:F,
});
pub type RangeCheck3Trace<F> = GenericTrace<RangeCheck3TraceRow<F>, 32, 0, 0>;


trace_row!(RangeCheck2FixedRow<F> {
 __L1__: F,
});
pub type RangeCheck2Fixed<F> = GenericTrace<RangeCheck2FixedRow<F>, 16, 1, 0>;

trace_row!(RangeCheck2TraceRow<F> {
 b1:F, b2:F, b3:F,
});
pub type RangeCheck2Trace<F> = GenericTrace<RangeCheck2TraceRow<F>, 16, 1, 0>;


trace_row!(RangeCheck1FixedRow<F> {
 __L1__: F,
});
pub type RangeCheck1Fixed<F> = GenericTrace<RangeCheck1FixedRow<F>, 8, 2, 0>;

trace_row!(RangeCheck1TraceRow<F> {
 a1:F, a2:F, a3:F, a4:F, a5:F, sel1:F, sel2:F, sel3:F,
});
pub type RangeCheck1Trace<F> = GenericTrace<RangeCheck1TraceRow<F>, 8, 2, 0>;


trace_row!(RangeCheck4FixedRow<F> {
 __L1__: F,
});
pub type RangeCheck4Fixed<F> = GenericTrace<RangeCheck4FixedRow<F>, 64, 3, 0>;

trace_row!(RangeCheck4TraceRow<F> {
 a1:F, a2:F, a3:F, a4:F, a5:F, a6:F, a7:F, a8:F, sel1:F, sel2:F,
});
pub type RangeCheck4Trace<F> = GenericTrace<RangeCheck4TraceRow<F>, 64, 3, 0>;


trace_row!(U16AirFixedRow<F> {
 RANGE: [F; 1], __L1__: F,
});
pub type U16AirFixed<F> = GenericTrace<U16AirFixedRow<F>, 65536, 3, 1>;

trace_row!(U16AirTraceRow<F> {
 mul:[F; 1],
});
pub type U16AirTrace<F> = GenericTrace<U16AirTraceRow<F>, 65536, 3, 1>;


trace_row!(MultiRangeCheck1FixedRow<F> {
 __L1__: F,
});
pub type MultiRangeCheck1Fixed<F> = GenericTrace<MultiRangeCheck1FixedRow<F>, 8, 4, 0>;

trace_row!(MultiRangeCheck1TraceRow<F> {
 a:[F; 3], sel:[F; 3], range_sel:[F; 3],
});
pub type MultiRangeCheck1Trace<F> = GenericTrace<MultiRangeCheck1TraceRow<F>, 8, 4, 0>;


trace_row!(MultiRangeCheck2FixedRow<F> {
 __L1__: F,
});
pub type MultiRangeCheck2Fixed<F> = GenericTrace<MultiRangeCheck2FixedRow<F>, 16, 5, 0>;

trace_row!(MultiRangeCheck2TraceRow<F> {
 a:[F; 2], sel:[F; 2], range_sel:[F; 2],
});
pub type MultiRangeCheck2Trace<F> = GenericTrace<MultiRangeCheck2TraceRow<F>, 16, 5, 0>;


trace_row!(RangeCheckDynamic1FixedRow<F> {
 __L1__: F,
});
pub type RangeCheckDynamic1Fixed<F> = GenericTrace<RangeCheckDynamic1FixedRow<F>, 256, 6, 0>;

trace_row!(RangeCheckDynamic1TraceRow<F> {
 colu:F, sel_7:F, sel_8:F, sel_16:F, sel_17:F,
});
pub type RangeCheckDynamic1Trace<F> = GenericTrace<RangeCheckDynamic1TraceRow<F>, 256, 6, 0>;


trace_row!(RangeCheckDynamic2FixedRow<F> {
 __L1__: F,
});
pub type RangeCheckDynamic2Fixed<F> = GenericTrace<RangeCheckDynamic2FixedRow<F>, 64, 7, 0>;

trace_row!(RangeCheckDynamic2TraceRow<F> {
 colu:F, sel_1:F, sel_2:F, sel_3:F, sel_4:F, sel_5:F,
});
pub type RangeCheckDynamic2Trace<F> = GenericTrace<RangeCheckDynamic2TraceRow<F>, 64, 7, 0>;


trace_row!(RangeCheckMixFixedRow<F> {
 __L1__: F,
});
pub type RangeCheckMixFixed<F> = GenericTrace<RangeCheckMixFixedRow<F>, 64, 8, 0>;

trace_row!(RangeCheckMixTraceRow<F> {
 a:[F; 4], b:[F; 2], c:[F; 1], range_sel:[F; 5],
});
pub type RangeCheckMixTrace<F> = GenericTrace<RangeCheckMixTraceRow<F>, 64, 8, 0>;


trace_row!(U8AirFixedRow<F> {
 RANGE: [F; 1], __L1__: F,
});
pub type U8AirFixed<F> = GenericTrace<U8AirFixedRow<F>, 256, 9, 0>;

trace_row!(U8AirTraceRow<F> {
 mul:[F; 1],
});
pub type U8AirTrace<F> = GenericTrace<U8AirTraceRow<F>, 256, 9, 0>;


trace_row!(SpecifiedRangesFixedRow<F> {
 OPID: [F; 14], VALS: [F; 14], __L1__: F,
});
pub type SpecifiedRangesFixed<F> = GenericTrace<SpecifiedRangesFixedRow<F>, 32768, 10, 0>;

trace_row!(SpecifiedRangesTraceRow<F> {
 mul:[F; 14],
});
pub type SpecifiedRangesTrace<F> = GenericTrace<SpecifiedRangesTraceRow<F>, 32768, 10, 0>;


values!(RangeCheck3AirGroupValues<F> {
 gsum_result: FieldExtension<F>,
});

values!(RangeCheck2AirGroupValues<F> {
 gsum_result: FieldExtension<F>,
});

values!(RangeCheck1AirGroupValues<F> {
 gsum_result: FieldExtension<F>,
});

values!(RangeCheck4AirGroupValues<F> {
 gsum_result: FieldExtension<F>,
});

values!(U16AirAirGroupValues<F> {
 gsum_result: FieldExtension<F>,
});

values!(MultiRangeCheck1AirGroupValues<F> {
 gsum_result: FieldExtension<F>,
});

values!(MultiRangeCheck2AirGroupValues<F> {
 gsum_result: FieldExtension<F>,
});

values!(RangeCheckDynamic1AirGroupValues<F> {
 gsum_result: FieldExtension<F>,
});

values!(RangeCheckDynamic2AirGroupValues<F> {
 gsum_result: FieldExtension<F>,
});

values!(RangeCheckMixAirGroupValues<F> {
 gsum_result: FieldExtension<F>,
});

values!(U8AirAirGroupValues<F> {
 gsum_result: FieldExtension<F>,
});

values!(SpecifiedRangesAirGroupValues<F> {
 gsum_result: FieldExtension<F>,
});

pub const PACKED_INFO: &[(usize, usize, PackedInfoConst)] = &[
];