// WARNING: This file has been autogenerated from the PILOUT file.
// Manual modifications are not recommended and may be overwritten.
#![allow(clippy::all)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]

use proofman_common as common;
use proofman_common::GenericTrace;
use proofman_common::PackedInfoConst;
pub use proofman_macros::trace_row;
pub use proofman_macros::values;
use fields::PrimeField64;
use std::fmt;

#[allow(dead_code)]
type FieldExtension<F> = [F; 3];

pub const PILOUT_HASH: &str = "85dc34240a6bb08076ffeb2dc34e8cd260a9daffd4e76734816a4c512314e423";

pub const MERKLE_TREE_ARITY: u64 = 4;

//AIRGROUP CONSTANTS

pub const LOOKUP_AIRGROUP_ID: usize = 0;

//AIR CONSTANTS

pub const LOOKUP_0_AIR_IDS: &[usize] = &[0];

pub const LOOKUP_1_AIR_IDS: &[usize] = &[1];

pub const LOOKUP_2_12_AIR_IDS: &[usize] = &[2];

pub const LOOKUP_2_13_AIR_IDS: &[usize] = &[3];

pub const LOOKUP_2_15_AIR_IDS: &[usize] = &[4];

pub const LOOKUP_3_AIR_IDS: &[usize] = &[5];

  
trace_row!(Lookup0FixedRow<F> {
 __L1__: F,
});
pub type Lookup0Fixed<F> = GenericTrace<Lookup0FixedRow<F>, 1024, 0, 0>;

trace_row!(Lookup0TraceRow<F> {
 f:[F; 4], t:[F; 4], sel:[F; 2], mul:[F; 2],
});
pub type Lookup0Trace<F> = GenericTrace<Lookup0TraceRow<F>, 1024, 0, 0>;


trace_row!(Lookup1FixedRow<F> {
 __L1__: F,
});
pub type Lookup1Fixed<F> = GenericTrace<Lookup1FixedRow<F>, 1024, 0, 1>;

trace_row!(Lookup1TraceRow<F> {
 f:[F; 2], t:F, sel:[F; 2], mul:F,
});
pub type Lookup1Trace<F> = GenericTrace<Lookup1TraceRow<F>, 1024, 0, 1>;


trace_row!(Lookup2_12FixedRow<F> {
 __L1__: F,
});
pub type Lookup2_12Fixed<F> = GenericTrace<Lookup2_12FixedRow<F>, 4096, 0, 2>;

trace_row!(Lookup2_12TraceRow<F> {
 a1:F, b1:F, a2:F, b2:F, a3:F, b3:F, a4:F, b4:F, c1:F, d1:F, c2:F, d2:F, sel1:F, sel2:F, mul:F,
});
pub type Lookup2_12Trace<F> = GenericTrace<Lookup2_12TraceRow<F>, 4096, 0, 2>;


trace_row!(Lookup2_13FixedRow<F> {
 __L1__: F,
});
pub type Lookup2_13Fixed<F> = GenericTrace<Lookup2_13FixedRow<F>, 8192, 0, 3>;

trace_row!(Lookup2_13TraceRow<F> {
 a1:F, b1:F, a2:F, b2:F, a3:F, b3:F, a4:F, b4:F, c1:F, d1:F, c2:F, d2:F, sel1:F, sel2:F, mul:F,
});
pub type Lookup2_13Trace<F> = GenericTrace<Lookup2_13TraceRow<F>, 8192, 0, 3>;


trace_row!(Lookup2_15FixedRow<F> {
 __L1__: F,
});
pub type Lookup2_15Fixed<F> = GenericTrace<Lookup2_15FixedRow<F>, 32768, 0, 4>;

trace_row!(Lookup2_15TraceRow<F> {
 a1:F, b1:F, a2:F, b2:F, a3:F, b3:F, a4:F, b4:F, c1:F, d1:F, c2:F, d2:F, sel1:F, sel2:F, mul:F,
});
pub type Lookup2_15Trace<F> = GenericTrace<Lookup2_15TraceRow<F>, 32768, 0, 4>;


trace_row!(Lookup3FixedRow<F> {
 __L1__: F,
});
pub type Lookup3Fixed<F> = GenericTrace<Lookup3FixedRow<F>, 16384, 0, 5>;

trace_row!(Lookup3TraceRow<F> {
 c1:F, d1:F, c2:F, d2:F, mul1:F, mul2:F,
});
pub type Lookup3Trace<F> = GenericTrace<Lookup3TraceRow<F>, 16384, 0, 5>;


values!(Lookup0AirGroupValues<F> {
 gsum_result: FieldExtension<F>,
});

values!(Lookup1AirGroupValues<F> {
 gsum_result: FieldExtension<F>,
});

values!(Lookup2_12AirGroupValues<F> {
 gsum_result: FieldExtension<F>,
});

values!(Lookup2_13AirGroupValues<F> {
 gsum_result: FieldExtension<F>,
});

values!(Lookup2_15AirGroupValues<F> {
 gsum_result: FieldExtension<F>,
});

values!(Lookup3AirGroupValues<F> {
 gsum_result: FieldExtension<F>,
});

pub const PACKED_INFO: &[(usize, usize, PackedInfoConst)] = &[
];