// WARNING: This file has been autogenerated from the PILOUT file.
// Manual modifications are not recommended and may be overwritten.
#![allow(clippy::all)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]

use proofman_common as common;
use proofman_common::GenericTrace;
use proofman_common::PackedInfoConst;
pub use proofman_macros::trace_row;
pub use proofman_macros::values;
use fields::PrimeField64;
use std::fmt;

#[allow(dead_code)]
type FieldExtension<F> = [F; 3];

pub const PILOUT_HASH: &str = "c26855220153e3911866b19eb46995bdab3a243a259875673c17589f1c2960dd";

pub const MERKLE_TREE_ARITY: u64 = 4;

//AIRGROUP CONSTANTS

pub const ONE_INSTANCE_PROD_AIRGROUP_ID: usize = 0;

pub const ONE_INSTANCE_SUM_AIRGROUP_ID: usize = 1;

//AIR CONSTANTS

pub const AIR_PROD_AIR_IDS: &[usize] = &[0];

pub const AIR_SUM_AIR_IDS: &[usize] = &[0];

  
trace_row!(AirProdFixedRow<F> {
 __L1__: F,
});
pub type AirProdFixed<F> = GenericTrace<AirProdFixedRow<F>, 256, 0, 0>;

trace_row!(AirProdTraceRow<F> {
 a:F, b:F, c:F,
});
pub type AirProdTrace<F> = GenericTrace<AirProdTraceRow<F>, 256, 0, 0>;


trace_row!(AirSumFixedRow<F> {
 __L1__: F,
});
pub type AirSumFixed<F> = GenericTrace<AirSumFixedRow<F>, 256, 1, 0>;

trace_row!(AirSumTraceRow<F> {
 a:F, b:F, c:F,
});
pub type AirSumTrace<F> = GenericTrace<AirSumTraceRow<F>, 256, 1, 0>;


pub const PACKED_INFO: &[(usize, usize, PackedInfoConst)] = &[
];